# Generated by Django 5.0.6 on 2024-06-18 22:25

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_about_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/', verbose_name='תמונה')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='כיתוב')),
            ],
            options={
                'verbose_name': 'תמונת קרוסלה',
                'verbose_name_plural': 'תמונות קרוסלה',
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
    ]
